In [15]:
import pandas as pd

In [16]:
sent = pd.read_csv('./data/sentiment.csv', index_col = 0)
sent = sent[sent['keyword'] != '탑마트']
sent

   keyword  sentiment_score
0      CGV         0.726648
1       LH         0.711766
2     갤러리아         0.752768
3      경상대         0.736908
4       남강         0.726113
5     롯데마트         0.676764
6      롯데몰         0.700681
7    롯데시네마         0.669798
8     메가박스         0.688804
9    모다아울렛         0.715585
10    엠비씨네         0.810106
11     이마트         0.695202
12    중앙시장         0.724921
13     진주성         0.759389
14     진주역         0.713217
15     칠암캠         0.761520
17    홈플러스         0.699425

In [57]:
location_data = {
    "CGV": {"address": "경상남도 진주시 에나로127번길 30", "latitude": 35.180660, "longitude": 128.143954},
    "LH": {"address": "경상남도 진주시 충의로 19", "latitude": 35.180660, "longitude": 128.143954},
    "갤러리아": {"address": "경상남도 진주시 진주대로 1095", "latitude": 35.180660, "longitude": 128.143954},
    "경상대": {"address": "경상남도 진주시 진주대로 501", "latitude": 35.152120, "longitude": 128.104720},
    "남강": {"address": "경남 진주시 강남로 320", "latitude": 35.189376, "longitude": 128.082690},
    "롯데마트": {"address": "경상남도 진주시 동진로 440", "latitude": 35.180660, "longitude": 128.143954},
    "롯데몰": {"address": "경상남도 진주시 동진로 440", "latitude": 35.180660, "longitude": 128.143954},
    "롯데시네마": {"address": "경상남도 진주시 동진로 440", "latitude": 35.180660, "longitude": 128.143954},
    "메가박스": {"address": "경상남도 진주시 진양호로 521", "latitude": 35.180660, "longitude": 128.143954},
    "모다아울렛": {"address": "경상남도 진주시 정촌면 삼일로105번길 15", "latitude": 35.180660, "longitude": 128.143954},
    "엠비씨네": {"address": "경남 진주시 가호로 13", "latitude": 35.180660, "longitude": 128.143954},
    "이마트": {"address": "경상남도 진주시 진양호로 477", "latitude": 35.180660, "longitude": 128.143954},
    "중앙시장": {"address": "경상남도 진주시 진양호로547번길 8-1", "latitude": 35.180660, "longitude": 128.143954},
    "진주성": {"address": "경상남도 진주시 남강로 626", "latitude": 35.189376, "longitude": 128.082690},
    "진주역": {"address": "경상남도 진주시 개양로 114 116번길 33", "latitude": 35.180660, "longitude": 128.143954},
    "칠암캠": {"address": "경상남도 진주시 동진로 33", "latitude": 35.179100, "longitude": 128.094839},
    "홈플러스": {"address": "경남 진주시 대신로 304", "latitude": 35.180660, "longitude": 128.143954}
}

# 주소, 위도, 경도 컬럼 추가
sent['address'] = sent['keyword'].map(lambda x: location_data[x]['address'])
sent['latitude'] = sent['keyword'].map(lambda x: location_data[x]['latitude'])
sent['longitude'] = sent['keyword'].map(lambda x: location_data[x]['longitude'])
sent

   keyword  sentiment_score                    address   latitude   longitude
0      CGV         0.726648       경상남도 진주시 에나로127번길 30  35.180660  128.143954
1       LH         0.711766            경상남도 진주시 충의로 19  35.180660  128.143954
2     갤러리아         0.752768         경상남도 진주시 진주대로 1095  35.180660  128.143954
3      경상대         0.736908          경상남도 진주시 진주대로 501  35.152120  128.104720
4       남강         0.726113             경남 진주시 강남로 320  35.189376  128.082690
5     롯데마트         0.676764           경상남도 진주시 동진로 440  35.180660  128.143954
6      롯데몰         0.700681           경상남도 진주시 동진로 440  35.180660  128.143954
7    롯데시네마         0.669798           경상남도 진주시 동진로 440  35.180660  128.143954
8     메가박스         0.688804          경상남도 진주시 진양호로 521  35.180660  128.143954
9    모다아울렛         0.715585   경상남도 진주시 정촌면 삼일로105번길 15  35.180660  128.143954
10    엠비씨네         0.810106              경남 진주시 가호로 13  35.180660  128.143954
11     이마트         0.695202          경상남도 진주시 진양호로 477  35.180660  128.143954
12    중앙시장         0.724921     경상남도 진주시 진양호로547번길 8-1  35.180660  128.143954
13     진주성         0.759389           경상남도 진주시 남강로 626  35.189376  128.082690
14     진주역         0.713217  경상남도 진주시 개양로 114 116번길 33  35.180660  128.143954
15     칠암캠         0.761520            경상남도 진주시 동진로 33  35.179100  128.094839
17    홈플러스         0.699425             경남 진주시 대신로 304  35.180660  128.143954

In [ ]:
import requests
from geopy.geocoders import Nominatim

# geocoder 초기화 (user_agent 지정 필수)
geolocator = Nominatim(user_agent="my_app")

def get_coords(address):
    loc = geolocator.geocode(address, timeout=10)
    if loc is None:
        # 주소를 못 찾았을 때 처리: 예외를 던지거나 (None, None) 리턴
        print(f"⚠️ 주소를 찾을 수 없습니다: {address}")
        return None, None
    return loc.latitude, loc.longitude

def osrm_distance(addr1, addr2, osrm_url="http://router.project-osrm.org"):
    c1 = get_coord(addr1)
    c2 = get_coord(addr2)
    coords = f"{c1[0]},{c1[1]};{c2[0]},{c2[1]}"
    url = f"{osrm_url}/route/v1/driving/{coords}?overview=false"
    res = requests.get(url).json()
    summary = res['routes'][0]['distance'], res['routes'][0]['duration']
    return summary[0]/1000 #, summary[1]/60  # km, min

# 사용 예
o = "서울 종로구 세종로 1-68"
d = "서울 중구 세종대로 110"
dist = osrm_distance(o, d)
dist

In [ ]:
jinju = pd.read_csv('./data/jinju.csv', index_col = 0)
jinju = jinju.iloc[:4]
print(jinju.shape)
jinju

(4, 20)

,시군구,번지,도로조건,계약면적(㎡),계약년월,계약일,보증금(만원),월세(만원),건축년도,도로명,경도,위도,year,month,location,전월세전환율,전세전환가격,coivd,price_per_m2,전월세구분_월세
0,경상남도 진주시 가좌동,1***,25,12.00,201902,16,200,35,2016,가좌길74번길,128.105889,35.157466,2019,2,경상남도 진주시 가좌동 가좌길74번길,5.1,8435,0,702.916667,True
1,경상남도 진주시 가좌동,1***,8,12.00,201901,5,4500,0,2016,가좌길78번길,128.105889,35.157466,2019,1,경상남도 진주시 가좌동 가좌길78번길,5.3,4500,0,375.000000,False
2,경상남도 진주시 가좌동,1***,8,14.20,201906,25,300,32,2016,가좌길60번길,128.106121,35.158214,2019,6,경상남도 진주시 가좌동 가좌길60번길,5.3,7545,0,531.338028,True
3,경상남도 진주시 가좌동,1***,12,14.85,201902,20,500,35,2019,가좌길64번길,128.105966,35.156961,2019,2,경상남도 진주시 가좌동 가좌길64번길,5.1,8735,0,588.215488,True

In [ ]:
# 안전하게 osrm_distance 호출하는 래퍼 함수
def safe_osrm_distance(origin, dest):
    try:
        return osrm_distance(origin, dest)
    except Exception as e:
        # 에러 메시지 출력(필요시 삭제)
        print(f"⚠️ 거리 계산 오류: {origin} → {dest} ({e})")
        return None

# 반복문을 돌며 각 sent 주소마다 컬럼 생성
for idx, sent_row in sent.reset_index(drop=True).iterrows():
    keyword = sent_row.keyword.replace(" ", "_")
    col_name = f"dist_{keyword}"
    addr = sent_row['address']
    
    # apply 대신 progress_apply 써도 됩니다
    jinju[col_name] = jinju['location'].apply(
        lambda rn: safe_osrm_distance(rn, addr)
    )

# 결과 확인
jinju

⚠️ 거리 계산 오류: 경상남도 진주시 가좌동 가좌길74번길 → 경남남도 진주시 개양로 114 116번길 33 ('NoneType' object has no attribute 'longitude')
⚠️ 거리 계산 오류: 경상남도 진주시 가좌동 가좌길78번길 → 경남남도 진주시 개양로 114 116번길 33 ('NoneType' object has no attribute 'longitude')
⚠️ 거리 계산 오류: 경상남도 진주시 가좌동 가좌길60번길 → 경남남도 진주시 개양로 114 116번길 33 ('NoneType' object has no attribute 'longitude')
⚠️ 거리 계산 오류: 경상남도 진주시 가좌동 가좌길64번길 → 경남남도 진주시 개양로 114 116번길 33 ('NoneType' object has no attribute 'longitude')

,시군구,번지,도로조건,계약면적(㎡),계약년월,계약일,보증금(만원),월세(만원),건축년도,도로명,...,dist_롯데시네마,dist_메가박스,dist_모다아울렛,dist_엠비씨네,dist_이마트,dist_중앙시장,dist_진주성,dist_진주역,dist_칠암캠,dist_홈플러스
0,경상남도 진주시 가좌동,1***,25,12.00,201902,16,200,35,2016,가좌길74번길,...,3.7968,5.1946,4.0113,1.1232,5.6523,5.6097,8.9219,None,3.7968,4.3089
1,경상남도 진주시 가좌동,1***,8,12.00,201901,5,4500,0,2016,가좌길78번길,...,3.7400,5.1379,4.0810,1.0665,5.5955,5.5530,8.9916,None,3.7400,4.2083
2,경상남도 진주시 가좌동,1***,8,14.20,201906,25,300,32,2016,가좌길60번길,...,3.9212,5.3190,4.0661,1.2476,5.7767,5.7341,8.9767,None,3.9212,4.3894
3,경상남도 진주시 가좌동,1***,12,14.85,201902,20,500,35,2019,가좌길64번길,...,3.8854,5.2832,4.0293,1.2118,5.7409,5.6983,8.9399,None,3.8854,4.3269

In [ ]:
jinju

,시군구,번지,도로조건,계약면적(㎡),계약년월,계약일,보증금(만원),월세(만원),건축년도,도로명,...,dist_롯데시네마,dist_메가박스,dist_모다아울렛,dist_엠비씨네,dist_이마트,dist_중앙시장,dist_진주성,dist_진주역,dist_칠암캠,dist_홈플러스
0,경상남도 진주시 가좌동,1***,25,12.00,201902,16,200,35,2016,가좌길74번길,...,3.7968,5.1946,4.0113,1.1232,5.6523,5.6097,8.9219,None,3.7968,4.3089
1,경상남도 진주시 가좌동,1***,8,12.00,201901,5,4500,0,2016,가좌길78번길,...,3.7400,5.1379,4.0810,1.0665,5.5955,5.5530,8.9916,None,3.7400,4.2083
2,경상남도 진주시 가좌동,1***,8,14.20,201906,25,300,32,2016,가좌길60번길,...,3.9212,5.3190,4.0661,1.2476,5.7767,5.7341,8.9767,None,3.9212,4.3894
3,경상남도 진주시 가좌동,1***,12,14.85,201902,20,500,35,2019,가좌길64번길,...,3.8854,5.2832,4.0293,1.2118,5.7409,5.6983,8.9399,None,3.8854,4.3269